// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIilFWcOSZ5SI4DnZEcB3EWMIpSy4Akfo',
    appId: '1:450827236433:android:f97ba2f9d804d73d1a3470',
    messagingSenderId: '450827236433',
    projectId: 'fitnessapp-f535a',
    storageBucket: 'fitnessapp-f535a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-E1suVwbxwArxfirX5_Vx1RyJFMY0Rzw',
    appId: '1:450827236433:ios:98717bd82c0f5e3d1a3470',
    messagingSenderId: '450827236433',
    projectId: 'fitnessapp-f535a',
    storageBucket: 'fitnessapp-f535a.appspot.com',
    androidClientId:
        '450827236433-s9uqs856uqeqmld45j3ovu48bb4g5591.apps.googleusercontent.com',
    iosClientId:
        '450827236433-ep4m5dd6hnp380h2otus5kn67o5h9q85.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphafitness',
  );
}
